steps:
  # Install Flutter SDK && Build Flutter Web app
  - name: 'cirrusci/flutter'
    entrypoint: /bin/sh
    args: ['-c', 'flutter pub get && flutter build web --dart-define=MODE=release --base-href="/" --web-renderer html']
  # Upload to GAE
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']
