steps:
  # Install Melos
#  - name: melosjs/melos
#    entrypoint: melos
#    args: [ "install" ]
  # Install Flutter SDK && Build Flutter Web app
  - name: 'cirrusci/flutter'
    entrypoint: /bin/sh
    args: ['-c', 'cd packages/daifuku/ && flutter pub get && flutter build web --dart-define=MODE=debug --base-href="/" --web-renderer html']
  # Upload to GAE
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - '-c'
    - |
      ls
      cd packages/daifuku/
      ls
      gcloud app deploy app.yaml
     
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args: ['app', 'deploy', 'app.yaml']
