name: daifuku
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: '>=3.3.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  dio: ^4.0.6
  flutter_riverpod: ^2.3.0
  flutter_easyloading: ^3.0.5
  go_router: ^6.0.8
  url_strategy: ^0.2.0
  flutter_adaptive_scaffold: ^0.1.0
  drag_and_drop_lists: ^0.3.3
  flutter_animated_dialog: ^2.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  shared_preferences: ^2.0.18
  pull_to_refresh: ^2.0.0
  grpc: ^3.1.0
  protobuf: ^2.1.0
  build_grpc_channel: ^0.5.0
  grpc_api:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.5.1
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
