// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmls4VC541weVge7sJsjIvCGZKY6Sfxe0',
    appId: '1:157083083857:web:0412b4f21ef90a403c8470',
    messagingSenderId: '157083083857',
    projectId: 'testflutterweb-f0895',
    authDomain: 'testflutterweb-f0895.firebaseapp.com',
    storageBucket: 'testflutterweb-f0895.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKHOP7bfTzOoRKaYZZwLX5qkRZ8pMnVTM',
    appId: '1:157083083857:android:363437e867af96033c8470',
    messagingSenderId: '157083083857',
    projectId: 'testflutterweb-f0895',
    storageBucket: 'testflutterweb-f0895.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWPjY_9pp0k4dISKlU9etrqOhJj4XO6Vw',
    appId: '1:157083083857:ios:fc598565c1188a0d3c8470',
    messagingSenderId: '157083083857',
    projectId: 'testflutterweb-f0895',
    storageBucket: 'testflutterweb-f0895.appspot.com',
    iosClientId:
        '157083083857-1lhi8q24fq4dschq4no3uj67ng0s74vg.apps.googleusercontent.com',
    iosBundleId: 'com.example.githubActionsFlutterweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWPjY_9pp0k4dISKlU9etrqOhJj4XO6Vw',
    appId: '1:157083083857:ios:fc598565c1188a0d3c8470',
    messagingSenderId: '157083083857',
    projectId: 'testflutterweb-f0895',
    storageBucket: 'testflutterweb-f0895.appspot.com',
    iosClientId:
        '157083083857-1lhi8q24fq4dschq4no3uj67ng0s74vg.apps.googleusercontent.com',
    iosBundleId: 'com.example.githubActionsFlutterweb',
  );
}
