name: build_and_deploy

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, closed]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      is_build: false

    steps:
      # Set environment variables
      - name: Set environment variables (debug)
        if: github.event.pull_request.base.ref == 'develop'
        run: echo "MY_VARIABLE=debug" >> $GITHUB_ENV
      
      - name: Set environment variables (stg)
        if: github.event.pull_request.base.ref == 'release'
        run: echo "MY_VARIABLE=stg" >> $GITHUB_ENV
        
      - name: Set environment variables (release)
        if: github.event.pull_request.base.ref == 'main'
        run: echo "MY_VARIABLE=release" >> $GITHUB_ENV

      - name: Test PR type
        run: |
          if [ "${{ github.event.action }}" == "closed" ]; then
            echo "::set-env name=is_build::true"
          else
            echo "::set-env name=is_build::false"
          fi

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.5' # 指定 Flutter 版本

      - name: Clean and Install pub
        run: |
          flutter clean
          flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Check for the existence of unformatted files
        run: dart format --set-exit-if-changed lib/

      - name: Metrics project
        run: flutter pub run dart_code_metrics:metrics analyze lib/

      - name: Test project
        run: flutter test

      - name: Build Web
        if: "${{ env.is_build }}" == "true"
        run: |
          flutter build web --dart-define=MODE="${{ env.MY_VARIABLE }}" --base-href="/TestFlutterWebGithubActions/" --web-renderer html
          
      - name: Deploy to GitHub Pages
        if: "${{ env.is_build }}" == "true"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build/web

      - name: Configure SMTP server
        if: "${{ env.is_build }}" == "true"
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: songjichao225@163.com,songjichao225@sina.com
          subject: 'Build completed successfully_'
          body: 'Your build TestFlutterWebGithubActions project has completed successfully.'

