name: build_and_deploy

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, closed]
  workflow_dispatch:

jobs:
  job_check:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Clean and Install pub
        run: |
          flutter clean
          flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Check for the existence of unformatted files
        run: dart format --set-exit-if-changed lib/

      - name: Metrics project
        run: flutter pub run dart_code_metrics:metrics analyze lib/

      - name: Test project
        run: flutter test