name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, closed]
  workflow_dispatch:

jobs:
  job_check:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'

      - name: Install Melos
        uses: bluefireteam/melos-action@v1

      - name: Analyze project
        run: melos analyze

      - name: Metrics project
        run: melos metrics

      - name: Check for the existence of unformatted files
        run: melos format:ci

      - name: Run unit tests
        run: melos run test
